#pragma config(Sensor, dgtl1,  sonic,          sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  limit,          sensorTouch)
#pragma config(Sensor, dgtl4,  encoderleft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  encoderright,   sensorQuadEncoder)
#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*The forwardfortime function makes to robot move forwards
at a specified speed for a specified time. */
void forwardfortime (int speed, int time) {
  motor[leftmotor] = speed;
  motor[rightmotor] = speed;
  wait1Msec(time);
  motor[leftmotor] = 0;
  motor[rightmotor] = 0;
}
/*The setmotorspeed function simply sets the speed of both
motors at once. Saving space and time. (For the coder)*/
void setmotorspeed (int speed) {
  motor[leftmotor] = speed;
  motor[rightmotor] = speed;
}
void gotobin () {

}
/* This function automatically does a u-turn.
True = right turn, False = left turn */
void uturn (bool direction) {
  if (direction == true) {
    SensorValue(leftencode) = 0;
    SensorValue(rightencode) = 0;
    while (SensorValue(leftencode) > -160) {
      motor[leftmotor] = 127;
    	motor[rightmotor] = -127;
    }
    setmotorspeed(127);
    wait1Msec(500);
  if (direction == false) {
    SensorValue(leftencode) = 0;
    SensorValue(rightencode) = 0;
    while (SensorValue(leftencode) < 160) {
      motor[leftmotor] = -127;
    	motor[rightmotor] = 127;
    }
    setmotorspeed(0);
  }
}

//Beginning the autonomous operation of the robot.
task main() {
  SensorValue(encoderright) = 0;
  SensorValue(encoderleft) = 0;
  while (true) {
    while (SensorValue(sonic) > 10) {
      setmotorspeed = 127;

    }
    break; //Stop the code, since this is just a test
  }
}
